### ISSUE TITLE
Web Flashing Doesnt Work

### ISSUE THREAD

**Issue by mbt28** [geo-tp/ESP32-Bus-Pirate#27]
Hello

Web flashing for esp32-s3 devkit doesnt work. I checked the webflasher source code and it seems binary file is missing in firmware folder.

https://geo-tp.github.io/ESP32-Bus-Pirate/webflasher/firmwares/bus_pirate_08_s3devkit.bin

**Comment by geo-tp** [comment]
I just added the web flasher and forgot about this bin. Thanks for the report.

Fixed, you can now flash the firmware

**Comment by mbt28** [comment]
Hello,

Thank you for quick fix however I still cannot upload it. It says prepearing the installation however nothing happens. I use chrome on raspian. 

```
uname -r
6.12.42-v8-16k+

lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 12 (bookworm)
Release:	12
Codename:	bookworm
```

I was able to flash it with success using esptool however the application doesnt work:
`sudo /home/$USER/esptool/bin/python3.11 /home/$USER/esptool/bin/esptool.py  --chip esp32s3 --port /dev/ttyACM0 --baud 460800 write_flash -z 0x0 bus_pirate_08_s3devkit.bin`

I am getting:
```
ESP-ROM:esp32s3-20210327
Build:Mar 27 2021
rst:0x1 (POWERON),boot:0xb (SPI_FAST_FLASH_BOOT)
SPIWP:0xee
mode:DIO, clock div:1
load:0x3fce3808,len:0x4bc
load:0x403c9700,len:0xbd8
load:0x403cc700,len:0x2a0c
entry 0x403c98d0
```

**Comment by geo-tp** [comment]
The web flasher hangs on Raspberry Pi  most likely because of Linux permissions, I just flashed it with no error with a linux system and the dev kit.

try this command to grant permissions to the usb interface
`sudo setfacl -m u:$USER:rw /dev/ttyACM0`

**Comment by mbt28** [comment]
I found the issue after trying with other computers. I flashed it with https://espressif.github.io/esptool-js/, baud rate should be 115200 otherwise it doesnt work. Anyway as per discussed in issue https://github.com/geo-tp/ESP32-Bus-Pirate/issues/24 I flashed it to 0x0. But it seems like it doesnt flash anything before 0x1. So I am just getting output below. What I am doing wrong? (I erased the flash before)

```
ESP-ROM:esp32s3-20210327
Build:Mar 27 2021
rst:0x1 (POWERON),boot:0xb (SPI_FAST_FLASH_BOOT)
SPIWP:0xee
mode:DIO, clock div:1
load:0x3fce3808,len:0x4bc
load:0x403c9700,len:0xbd8
load:0x403cc700,len:0x2a0c
entry 0x403c98d0
```
Many thanks

**Comment by geo-tp** [comment]
it seems the same issue as here : https://github.com/geo-tp/ESP32-Bus-Pirate/issues/11

You probably don't use the correst USB port

**Comment by mbt28** [comment]
Hello,

Indeed it works with native usb port! Thank you so much for your help, I cant wait to try it. :)
